name: Build and Publish Wheels

on:
  release:
    types:
      - published
  # uncomment this during debugging
  pull_request:
    branches: [ main ]
  
  # To run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Configure git for long paths
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true

      - name: Check out the code
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set GDAL Submodule to Specific Tag
        run: |
          git submodule update --init --recursive

      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Cache build artifacts
      - name: Cache build artifacts
        uses: actions/cache@v4.1.0
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.cpp', '**/*.h', '**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-

      # Build GDAL and package
      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.21.2

      - uses: actions/upload-artifact@v4.4.0
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl


  testpypi:
    name: Publish package to TestPyPI
    needs:
    - build_wheels
    runs-on: ubuntu-latest

    environment:
      name: test-pypi

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4.1.8
      with:
        # unpacks all CIBW artifacts into dist/
        pattern: cibw-*
        path: dist
        merge-multiple: true
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
